services:
  ordersservice:
    image: ${DOCKER_REGISTRY-}ordersservice
    build:
      context: .
      dockerfile: OrdersService/Dockerfile
    environment:
        - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
        - OTEL_SERVICE_NAME=OrdersService.Api
    ports:
      - "8181:8080"

  paymentservice:
    image: ${DOCKER_REGISTRY-}paymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    environment:
        - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
        - OTEL_SERVICE_NAME=PaymentService.Api
    ports:
      - "8282:8080"

  sales-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Sales.Db
    environment:
      - SA_PASSWORD=helloWorld18
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: dashboard
    ports:
      - 18888:18888